error_codes = {
    '0': {'name': 'Success'},
    '1': {'name': 'P4 to C compilation failed'},
    '2': {'name': 'C compilation failed (meson)'},
    '3': {'name': 'C compilation failed'},
    '4': {'name': 'Too many iterations, possible infinite loop'},
    '5': {'name': 'Packets were unexpectedly dropped/sent'},
    '6': {'name': 'Execution finished with wrong output'},
    '7': {'name': 'Control flow requirements not met'},
    '124': {'name': 'Timeout error'},
    '134': {'name': 'Stack smashing'},
    '139': {'name': 'Segmentation fault'},
    '247': {'name': 'Timeout error (sigkill was needed instead of sigterm)'},
    '254': {'name': 'Execution interrupted'},
    '255': {'name': 'Switch execution error'},
}
